<html>
<head>
<title>ZFDemo | DEBUG</title>
<style>
caption {font-size:large; font-weight:bold}
table {margin:1em}
</style>
</head>
<!-- STAGE 6.  Render results in response to request. -->
<!-- Presentation model is accessed using "$this->" syntax. -->
<body>
<h3><?php echo $this->date ?></h3>

<?php
if (!count($this->tables)) {
    echo '<p style="color:maroon; font-weight:bold">ERROR: No tables found!</p>
          <p>Please see the <a href="http://framework.zend.com/wiki/x/7k8">instructions for installing the ZFDemo SQL Schema</a>.</p>';
    return;
}
?>

<hr>
<p>The tables below are shown purely for a sanity check to visually verify that the SQL schema loaded.</p>
<h3>Dumping ZFDemo Tables</h3>

<?php
foreach($this->tables as $name => $table) {
?>
    <table cellpadding=3 cellspacing=3 border=3 style='white-space: nowrap;'>
        <caption><?php echo $name ?></caption>
        <tr>
            <th>Field</th>
            <th>Type</th>
            <th>Null</th>
            <th>Key</th>
            <th>Default</th>
            <th>Extra</th>
        </tr>
<?php
            foreach($table as $row) {
                echo "<tr>\n";
                foreach($row as $col) {
                    echo "<td>", $this->escape($col), "</td>\n";
                }
                echo "</tr>\n";
            }
?>
    </table>
<?php
}
?>
    <hr noshade size=5>
    <pre><?php echo htmlentities(print_r($this->SERVER), ENT_QUOTES, 'UTF-8'); ?></pre>
