<!-- BEGIN: forum/views/scripts/addedInSectionDb.phtml -->
    <title>ZFDemo | ADMIN Edit</title>
</head>
<!-- STAGE 6: Render results in response to request. -->
<!-- Presentation model is accessed using "$this->" syntax. -->
<body>
<div style="float:right"><small>(Your timezone is: <?php echo $this->timezone ?>)</small></div>
<h3><?php echo $this->now ?> - Welcome <span style="color:maroon"><?php echo $this->username ?></span></h3>

<p>Edit support is added in "Section 10 DB".</p>

<!-- END: forum/views/scripts/addedInSectionDb.phtml -->
