<html><head><title>Distance to London</title></head>
<!-- STAGE 6: Render results in response to request. -->
<!-- Presentation model is accessed using "$this->" syntax. -->
<body>
<h1><?php echo $this->date ?></h1>

<?php if ($this->cities): ?>

    <table cellpadding=3 cellspacing=3 border=3 width=300>
        <caption>Cities within <?php echo $this->maxDistance ?> km of London:</caption>
        <tr>
            <th>City</th>
            <th>Distance</th>
        </tr>
<?php
        while (count($this->cities)) {
            echo "<tr><td>", $this->escape(array_pop($this->cities)),
                "</td><td>", $this->escape(array_pop($this->distances)), " km</td></tr>\n";
        }
?>
    </table>

<?php else: ?>

    <p>No cities are within <?php echo $this->escape($this->maxDistance) ?> km of London.</p>

<?php endif; ?>
    <p>Try changing the kilometers shown in the address bar ("request=10000").</p>
    <hr noshade size=5>
    <pre><?php echo htmlentities(print_r($this->SERVER), ENT_QUOTES, 'UTF-8'); ?></pre>
</body>
</html>
