<!-- BEGIN: default/views/scripts/logonLogoutForm.phtml -->
</head>
<body>
<h1>Welcome to the ZF Demo: <?php echo $this->sectionName ?></h1>

Logout?

<a href="<?php echo $this->baseUrl ?>/logon/logoff">Yes, return to home page.</a> 
|
<a href="<?php echo $this->baseUrl ?>/logon/logout">Login with a different identity.</a> 
|
<a href="<?php echo $this->baseUrl ?>">No</a>
<!-- END: default/views/scripts/logonLogoutForm.phtml -->
