<html><head><title>ZF Demo Install Test Page</title></head>
<body>
<h1>Welcome to the ZF Demo Install Test</h1>
<ol>
<li><a href="index.php/forum/">Continue Test</a></li>
<li><a href="index.php/env">Zend Environment Information</a> (ZF incubator installation required)</li>
<li><a href="http://framework.zend.com/wiki/display/ZFDEV/Tutorial">Online Tutorial</a></li>
</ol>

<hr><h3>UTF-8 Web Browser Rendering Test:</h3>
<p>Umlauts and accented characters: ÄËÏÖÜäëïöü ß áéíóú âêîôû àèìòù</p>

<p>“The quick brown fox jumps over the ‘lazy’ dog.”</p>

<p>„Falsches Üben von ‚Xylophonmusik‘ quält jeden größeren Zwerg.“</p>

<p>»Angle ›quotation‹ marks«</p>

<p>n–dash em—dash</p>

<p>Ellipsis…</p>

<p>Euro € sign</p>

<p>中文</p>

<p>日本語</p>

<p>русский язык</p>
