<!-- BEGIN: default/views/scripts/indexIndex.phtml -->
<h1>Welcome to the ZF Demo: <?php echo $this->sectionName ?></h1>

<p>
The file config/config.ini contains configuration information.
This information includes connection details for your database.
The ZFDemo currently only supports a MySQL database.
Please see the <a href="http://framework.zend.com/wiki/x/1E8">tutorial instructions</a> for more information.
</p>

<p>When checking for the ZF Demo tables in your configured database instance, a problem was detected.  If you have not yet installed the tables needed by this demo, please 
<a href="<?php echo $this->baseUrl ?>/index/reset">Resest/Load/Restore DB (<span style="color:red"><b>deletes</b></span> all changes and posts)</a>.</p>

<!-- END: default/views/scripts/indexIndex.phtml -->
