<!DOCTYPE html
PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US" dir="ltr">

    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
        <link rel="shortcut icon" href="/zfgrid/images/favicon.ico" type="image/x-icon" />
        <link rel="stylesheet" type="text/css" href="/zfgrid/css/screen.css" media="all" />
        <title>Zend Framework 1.0 MVC/Database example application</title>
    </head>

    <body>
        <h1>Zend Framework 1.0 MVC/Database example application</h1>
        <p>
        <a href="/zfgrid/index">Return to home</a>
        </p>

        <table cellspacing="0" cellpadding="2">

            <tr class="rowHead">
                <? foreach ($this->tableInfo['cols'] as $columnName): ?>
                <th>
                    <a href="/zfgrid/grid/show/table/<?= $this->tableInfo['name'] ?>/order/<?= $columnName ?>">
                    <?= $columnName ?>
                    </a>
                </th>
                <? endforeach; ?>
            </tr>

            <?php
            $i = 0;
            $stripeClass = array('rowEven', 'rowOdd');
            ?>

            <? foreach ($this->rowset as $row): ?>
            <tr class="<?= $stripeClass[$i++%2] ?>">

                <? foreach ($this->tableInfo['cols'] as $columnName): ?>
                <td>
                    <?= $this->escape($row->$columnName) ?>
                </td>
                <? endforeach; ?>

            </tr>
            <? endforeach; ?>

        </table>
    </body>

</html>


<!--
 - Zend Framework
 -
 - LICENSE
 -
 - This source file is subject to the new BSD license that is bundled
 - with this package in the file LICENSE.txt.
 - It is also available through the world-wide-web at this URL:
 - http://framework.zend.com/license/new-bsd
 - If you did not receive a copy of the license and are unable to
 - obtain it through the world-wide-web, please send an email
 - to license@zend.com so we can send you a copy immediately.
 -
 - @category   Zend
 - @package    Zend_Grid
 - @copyright  Copyright (c) 2005-2007 Zend Technologies USA Inc. (http://www.zend.com)
 - @license    http://framework.zend.com/license/new-bsd     New BSD License
 - @version    $Id: TestHelper.php 4528 2007-04-17 23:10:47Z darby $
 -->
